#!/usr/bin/env python3
"""Import the user-supplied study plan without importing its assistant instructions.

Usage: python3 scripts/import-study-plan.py /path/to/学习交接包.md
The generated file contains curriculum content only, never personal progress.
"""

import argparse
import hashlib
import json
from pathlib import Path
import re


def field(block: str, label: str, required: bool = True) -> str:
    match = re.search(rf"^\*\*{re.escape(label)}：\*\* (.+)$", block, re.MULTILINE)
    if match:
        return match.group(1).strip()
    if required:
        raise ValueError(f"Missing field: {label}")
    return ""


def parse_plan(source: str) -> dict:
    # Only section C is curriculum. Sections A/D contain handoff instructions;
    # section E is a separate personal-progress record and is never seeded here.
    curriculum = source.split("## C．", 1)[1].split("## D．", 1)[0]
    chapter_matches = list(re.finditer(r"^### 第(\d)章｜(.+)$", curriculum, re.MULTILINE))
    chapters = []
    for index, chapter_match in enumerate(chapter_matches):
        end = chapter_matches[index + 1].start() if index + 1 < len(chapter_matches) else len(curriculum)
        chapter_text = curriculum[chapter_match.end():end].split("### 4.", 1)[0]
        pack_matches = list(re.finditer(r"^#### ([1-8]-(?:\d{2}|R|P))｜(.+)$", chapter_text, re.MULTILINE))
        packs = []
        for pack_index, match in enumerate(pack_matches):
            pack_end = pack_matches[pack_index + 1].start() if pack_index + 1 < len(pack_matches) else len(chapter_text)
            block = chapter_text[match.end():pack_end]
            pack_id, title = match.groups()
            reading_time = field(block, "阅读与时间")
            time_match = re.fullmatch(r"(.+)；约(.+)分钟。", reading_time)
            if not time_match:
                raise ValueError(f"Invalid reading/time field in {pack_id}")
            prompts = re.findall(r"^([1-3])\. (.+)$", block, re.MULTILINE)
            hints = dict(re.findall(r"^- 第([1-3])题：(.+)$", block, re.MULTILINE))
            kind = "review" if pack_id.endswith("-R") else "practice" if pack_id.endswith("-P") else "reading"
            if kind == "reading" and (len(prompts) != 3 or len(hints) != 3):
                raise ValueError(f"Expected three questions and hints in {pack_id}")
            book_practice = field(block, "原书同步练习", required=False)
            if not book_practice:
                book_practice = "\n\n".join([
                    field(block, "这一批怎么做"),
                    field(block, "原书范围"),
                ])
                # Preserve the actual experiment entry without fabricating an X pack.
                extra_lab = field(block, "本章额外实验/编程入口", required=False)
                if extra_lab:
                    book_practice += "\n\n额外实验/编程入口：" + extra_lab
            packs.append({
                "id": pack_id,
                "title": title,
                "kind": kind,
                "reading": time_match.group(1),
                "minutes": time_match.group(2),
                "output": field(block, "本份产物"),
                "bookPractice": book_practice,
                "questions": [{"id": f"{pack_id}-q{number}", "prompt": prompt, "hint": hints[number]} for number, prompt in prompts],
                "base": True,
            })
        chapters.append({"id": chapter_match.group(1), "title": chapter_match.group(2), "packs": packs})
    all_packs = [pack for chapter in chapters for pack in chapter["packs"]]
    counts = (len(chapters), len(all_packs), sum(len(pack["questions"]) for pack in all_packs))
    if counts != (8, 60, 132):
        raise ValueError(f"Incomplete source; expected 8 chapters / 60 packs / 132 questions, got {counts}")
    if len({pack["id"] for pack in all_packs}) != 60:
        raise ValueError("Duplicate pack IDs")
    return {
        "id": "computer-networking",
        "title": "计算机网络：自顶向下方法",
        "subtitle": "第 8 版 · 从原理到实践",
        "kind": "book",
        "description": "按学习包推进，保留阅读、自测、订正与伙伴互检。44 个阅读包、16 个章末作业入口，含 132 道自拟题；原书题以手中教材为准，可继续追加作业与实验。",
        "color": "#007aff",
        "chapters": chapters,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("--output", type=Path, default=Path(__file__).resolve().parents[1] / "src/data/study/networking.ts")
    args = parser.parse_args()
    raw = args.source.read_bytes()
    project = parse_plan(raw.decode("utf-8"))
    header = (
        "// Generated by scripts/import-study-plan.py from the user-provided learning plan.\n"
        f"// Source SHA-256: {hashlib.sha256(raw).hexdigest()}\n"
        "// 8 chapters · 60 base packs · 132 self-authored questions and hints. No personal progress.\n"
        'import type { StudyProject } from "../../lib/study-model";\n\n'
        'import { networkingChapterOne } from "./networking-chapter-one";\n'
        'import { networkingWiresharkPacks } from "./networking-wireshark";\n\n'
        "export const legacyNetworkingStudyProject: StudyProject = "
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    # Keep the separately maintained photographed exercises when regenerating the handoff.
    current = (Path(__file__).resolve().parents[1] / "src/data/study/networking.ts").read_text(encoding="utf-8")
    overlay = current[current.index("// The photographed first-chapter exercises"): ]
    args.output.write_text(header + json.dumps(project, ensure_ascii=False, indent=2) + ";\n\n" + overlay, encoding="utf-8")
    print(f"Imported 8 chapters, 60 packs and 132 questions into {args.output}")


if __name__ == "__main__":
    main()
